title: Manank Patni
description: My Portfolio
author: Manank Patni
logo: /hcz-jekyll-blog/static/img/0.jpg
github: https://github.com/Man-Jain
about: Blockchain Developer | Google Code-in Mentor | Django | Open Source Enthusiast | Core Developer at coala Association

baseurl: ""
url: ""

allowsearch: true

disqus_shortname: 
google_analytics: 

share:
  twitter_username: \#
  fb_appid: 000000000000


enableTags: true
tagarray: []

paginate: 20
per_page: 20
paginate_path: "/page:num/"
markdown: kramdown
gems: [jekyll-paginate, jekyll-gist]
